SYMBOLS = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'ADAUSDT',
    'XRPUSDT', 'DOGEUSDT', 'MATICUSDT', 'DOTUSDT', 'AVAXUSDT', 'LTCUSDT'
]

ALGORITHM = 'PPO'
TOTAL_TIMESTEPS = 1_000_000
STARTING_BALANCE = 10000

FEE_RATE = 0.001
LOOKBACK_WINDOW = 5 * 12 * 2 # 4 hours (5m * 12 = 1 hour * 4)
REBALANCE_FREQUENCY = 6 # every 15 minutes (3 * 5m)
RISK_FREE_RATE = -0.04
MAX_DRAWDOWN_PENALTY = 3.5
NORMALIZE_OBS = True

REWARD_HORIZON = 5 * 12 * 4 # 4 hours (5m * 12 = 1 hour * 4) 

REWARD_RETURN_WEIGHT = 1.25
REWARD_SHARPE_WEIGHT = 2.5
REWARD_DRAWDOWN_WEIGHT = 0.5
REWARD_VOLATILITY_WEIGHT = 0.3

NETWORK_SIZE = 'xlarge'

LEARNING_RATE = 0.0003
BATCH_SIZE = 64
N_STEPS = 2048

USE_WANDB = True
WANDB_PROJECT = 'crypto-portfolio-rl'

BENCHMARK_WEIGHT = 1.0
FUTURE_PROFIT_WEIGHT = 0.5
FUTURE_WINDOW = 6
RISK_ADJUSTMENT = True
DYNAMIC_PENALTIES = True
USE_ATTENTION_WEIGHTS = False
VOLATILITY_SCALING = True
