SYMBOLS = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'ADAUSDT',
    'XRPUSDT', 'DOGEUSDT', 'MATICUSDT', 'DOTUSDT', 'AVAXUSDT'
]

ALGORITHM = 'PPO'
TOTAL_TIMESTEPS = 100_000
STARTING_BALANCE = 10000

FEE_RATE = 0.001
LOOKBACK_WINDOW = 24
REBALANCE_FREQUENCY = 6
RISK_FREE_RATE = -0.04
MAX_DRAWDOWN_PENALTY = 3.0
NORMALIZE_OBS = True

REWARD_HORIZON = 12

REWARD_RETURN_WEIGHT = 1.0
REWARD_SHARPE_WEIGHT = 0.8
REWARD_DRAWDOWN_WEIGHT = 0.5
REWARD_VOLATILITY_WEIGHT = 0.3

NETWORK_SIZE = 'medium'

LEARNING_RATE = 0.0003
BATCH_SIZE = 64
N_STEPS = 2048

USE_WANDB = True
WANDB_PROJECT = 'crypto-portfolio-rl'
