LOOKBACK_DAYS = 16
WINDOW_SIZE =  LOOKBACK_DAYS * 24
NEXT_PRICE_PREDICTION = 24
NEXT_PRICE_PREDICTION_1 = 24 * (LOOKBACK_DAYS / 2)
NEXT_PRICE_PREDICTION_2 = 24 * LOOKBACK_DAYS
BATCH_SIZE = 64
EPOCHS = 1
LEARNING_RATE = 0.001